name: CI

on:
  push:
    branches:
      - '*develop*'
      - '*master*'
  pull_request:
    branches:
      - '*develop*'
      - '*master*'

jobs:
  cross_build:
    name: Cross-platform build and deploy
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      # 1️⃣ Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Install CMake (Linux)
      - name: Install CMake (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential git

      # 2️⃣ Install CMake (macOS)
      - name: Install CMake (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install cmake git

      # 2️⃣ Ensure CMake is available (Windows)
      - name: Ensure CMake is available (Windows)
        if: runner.os == 'Windows'
        run: |
          cmake --version
        shell: pwsh

      # 3️⃣ Build project
      - name: Build project
        run: |
          if [ "$RUNNER_OS" = "Linux" ] || [ "$RUNNER_OS" = "macOS" ]; then
            chmod +x ./ci.sh
            ./ci.sh
          else
            ./ci.bat
          fi
        shell: bash

      # 4️⃣ Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ runner.os }}
          path: |
            build/**
            bin/**
            *.exe
            *.out
            *.app
            *.zip
          retention-days: 7

      # 5️⃣ Download artifacts (optional test step)
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-${{ runner.os }}
          path: ./downloaded_artifacts

      # 6️⃣ Run built executable (optional sanity check)
      - name: Run built executable
        if: runner.os == 'Windows'
        run: |
          echo "Running built Windows executable..."
          Get-ChildItem -Path ./downloaded_artifacts -Recurse
          ./downloaded_artifacts/main.exe || echo "No executable found"
        shell: pwsh

      - name: Run built executable (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          echo "Running built binary..."
          chmod +x ./downloaded_artifacts/main* || true
          ./downloaded_artifacts/main* || echo "No executable found"
        shell: bash

      # 7️⃣ Deploy artifacts (example placeholder)
      - name: Deploy artifacts
        run: |
          echo "Deploying build artifacts..."
          echo "Build on $RUNNER_OS completed successfully."
        shell: bash
